apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-configmap
  labels:
    app: hello-world-configmap
spec:
  selector:
    matchLabels:
      app: hello-world-configmap
  template:
    metadata:
      labels:
        app: hello-world-configmap
    spec:
      containers:
      - name: hello-world-configmap
        image: "enabledocker/hello-world-configmap:1.0"
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "{{ .Values.app.port }}"
        - name: HELLOWORLD
          valueFrom:
            configMapKeyRef:
              name: hello-world
              key: helloworld
