apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-configmap
  name: hello-world-configmap
spec:
  ports:
  - port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
  selector:
    app: hello-world-configmap
  type: ClusterIP